name: Deployment Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:3333'
          config: baseUrl=http://localhost:3333
          spec: |
            cypress/integration/EditingTasks.js
            cypress/integration/TaskAddInvalid.js
            cypress/integration/TaskAddSuccess.js
            cypress/integration/ThemeTest.js
